		<?php 
		//estilos para la seccion
			$this->headLink()
						->prependStylesheet($this->basePath() . '/css/violet-bootstrap.min.css')	
		?>
				
		<?php
			$title = 'Cursos';
			$this -> headTitle($title);
		?>
	
		<?php $this->headScript()->captureStart() ?>
			function activeNav() {
				document.getElementById('nav-<?php echo $title; ?>').className = "active";
			}

			window.addEventListener('load', activeNav, false);
		<?php $this->headScript()->captureEnd() ?>
		
