<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Borrar Alumno';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($alumno->nombres); ?>'
	'<?php echo $this->escapeHtml($alumno->aPaterno); ?>'
    '<?php echo $this->escapeHtml($alumno->aMaterno); ?>' ?
	
</p>
<?php
$url = $this->url('escuela', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $alumno->idAlumno; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
