<?php
// module/Escuela/view/escuela/escuela/index.phtml:

$title = 'Alumnos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('escuela', array('action'=>'add'));?>">Inscribir Alumno</a>
</p>

<table class="table">
<tr>
    <th>Nombre</th>
    <th>Apellido Paterno</th>
	<th>Apellido Paterno</th>
    <th>Mail</th>
	<th>Tipo de estudiante</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($escuelas as $alumno) : ?>
<tr>
    <td><?php echo $this->escapeHtml($alumno->nombres);?></td>
	<td><?php echo $this->escapeHtml($alumno->aPaterno);?></td>
	<td><?php echo $this->escapeHtml($alumno->aMaterno);?></td>
	<td><?php echo $this->escapeHtml($alumno->mail);?></td>
	<td><?php echo $this->escapeHtml($alumno->tipoEstudiante);?></td>
    <td>
        <a href="<?php echo $this->url('escuela',
            array('action'=>'edit', 'id' => $alumno->idAlumno));?>">Edit</a>
        <a href="<?php echo $this->url('escuela',
            array('action'=>'delete', 'id' => $alumno->idAlumno));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<table class="table">
<tr>
    <th>Nombre</th>
    <th>Apellido Paterno</th>
	<th>Apellido Paterno</th>
    <th>Mail</th>
	<th>Tipo de estudiante</th>
    <th>&nbsp;</th>
</tr>

</tr>
<?php foreach ($profesores as $profesor) : ?>
<tr>
    <td><?php echo $this->escapeHtml($profesor->nombres);?></td>
	<td><?php echo $this->escapeHtml($profesor->aPaterno);?></td>
	<td><?php echo $this->escapeHtml($profesor->aMaterno);?></td>
	<td><?php echo $this->escapeHtml($profesor->mail);?></td>
</tr>
<?php endforeach; ?>
</table>